/**
 * File: apic_send_EOI.cpp
 *       An End Of Interrupt (EOI) is a signal sent to a Programmable Interrupt
 *       Controller (PIC) to indicate the completion of interrupt processing for
 *       a given interrupt. An EOI is used to cause a PIC to clear the
 *       corresponding bit in the In Service Register (ISR), and thus allow more
 *       interrupt requests of equal or lower priority to be generated by the
 *       PIC.
 *
 * Author: Rambod Rahmani <rambodrahmani@autistici.org>
 *         Created on 06/07/2019.
 */

#include "internal.h"
#include "apic.h"

extern "C" void apic_send_EOI()
{
    *IOAPIC_EOIR = 0;
}

